### ISSUE TITLE
Compile fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by braydonf** [comaeio/porosity#14]
Compiling on Ubuntu 16.04 will currently fail as the included boost library is 1.58 that will enter this branch and fail https://github.com/comaeio/porosity/blob/master/porosity/porosity/Common.h#L48 There also isn't any documentation about dependencies and installation steps and the necessity of `-std=c++1y` flag when compiling with g++ or boost versions needed.

More details with a fix at: https://github.com/comaeio/porosity/pull/13
Related: https://github.com/comaeio/porosity/issues/8

**Comment by beaugunderson** [comment]
`c++1y` should now be `c++14` I believe

**Comment by braydonf** [comment]
This issue really isn't fixed, not sure why it's closed.
