### ISSUE TITLE
Test results

### ISSUE THREAD

**Issue by beaugunderson** [comaeio/porosity#5]
I wrote a test script to audit the top 10,000 contracts by value stored; here's what I came up with:

- EVM errors: 3,635 (36.35%)
- use of unimplemented instruction: 5,544 (55.44%)
- contained >1 potential vulnerability: 1,468 (14.68%)
- timed out after 1 second: 709 (7.09%) (I found many contracts would run forever so capped runtime at 1 second)
- segfault: 3,524 (35.24%)
- unknown error: 29 (0.29%)

Worth noting that this used `--decompile` without `--abi`.

Will clean up and share test script and data at some point today; it might be useful to add it (or a subset of it) to a CI process.

**Comment by msuiche** [comment]
That would be great if you could share it, that will be very useful to improve support and regression tests.

**Comment by beaugunderson** [comment]
ok, I put it online here: https://github.com/beaugunderson/porosity-tests

**Comment by genecyber** [comment]
Thanks for this. Which env did you run this in? I’ve segfaults on Linux that I haven’t on windows.

**Comment by beaugunderson** [comment]
@genecyber macOS; I got segfaults but haven't chased them down
