### ISSUE TITLE
release pre-compiled binaries. 

### ISSUE THREAD

**Issue by genecyber** [comaeio/porosity#7]
I'm trying to build using MS Code and I'm having trouble building and thought to see if you had made a release.

**Comment by halsten** [comment]
Could you explain what the problem is? Maybe we could help you with it.

**Comment by patrickmn** [comment]
Linux: https://github.com/jpmorganchase/quorum/releases/download/v1.2.0/porosity

**Comment by kumarde** [comment]
@patrickmn thanks!
