### ISSUE TITLE
How to build in Linux?

### ISSUE THREAD

**Issue by exp10t** [comaeio/porosity#8]
I tried to make it in Ubuntu14.04. However, I got the following error:
g++    -c -o BasicBlocks.o BasicBlocks.cpp
g++    -c -o VMState.o VMState.cpp
In file included from VMState.cpp:18:0:
Porosity.h:22:36: fatal error: boost/dynamic_bitset.hpp: No such file or directory
 #include <boost/dynamic_bitset.hpp>
                                    ^
compilation terminated.
make: *** [VMState.o] Error 1

**Comment by beaugunderson** [comment]
do you have libboost-dev (or equivalent) installed?

---

**Comment by homakov** [comment]
Memory heavy?

```
 make
g++    -c -o Contract.o Contract.cpp
virtual memory exhausted: Cannot allocate memory
<builtin>: recipe for target 'Contract.o' failed
make: *** [Contract.o] Error 1
```
